name: Write the number of dot works down to README.md

on: [push]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main'
    
    - name: Install g++
      run: sudo apt-get install g++ -y
    
    - name: Compile and Run C++ Program
      run: |
        g++ counter.cpp -o counter -std=c++17
        ./counter > output.txt
    
    - name: Update README
      run: |
        COUNT=$(cat output.txt)
        README_CONTENT=$(cat README.md)
        echo -e "${README_CONTENT}\n今までで<>${COUNT}<>つのドット絵作品が描かれています。" > README.md
    
    - name: Commit and Push if Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add README.md
        git commit -m "Update README with .png file count" -a || echo "No changes to commit"
        git push
