name: Update README with Execution Result

on: [push]

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        ref: 'main' # デフォルトブランチ名に合わせてください
    
    - name: Install g++
      run: sudo apt-get install g++ -y
    
    - name: Compile and Run C++ Program
      run: |
        g++ counter.cpp -o counter -std=c++17
        ./counter > output.txt
    
    - name: Update README
      run: |
        COUNT=$(cat output.txt)
        sed -i '/<!-- PNG_COUNT_START -->/,/<!-- PNG_COUNT_END -->/c\<!-- PNG_COUNT_START -->\nThere are ${COUNT} PNG files in the dot-works directory.\n<!-- PNG_COUNT_END -->' README.md
    
    - name: Commit and Push if Changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git diff --quiet && git diff --staged --quiet || (git commit -am "Update README with .png file count" && git push)
