name: Get number of PNGs on dot-works

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install g++
      run: sudo apt-get install g++ -y
    - name: Compile C++ program
      run: g++ -std=c++17 -o count_png counter.cpp -lstdc++fs
    - name: Run C++ program
      run: ./counter
