name: Get number of PNGs on dot-works

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install g++
      run: sudo apt-get install g++ -y
    - name: Compile C++ program
      run: g++ counter.cpp -o counter -std=c++17
    - name: Run C++ program
      run: ./counter
